# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=40)),
                ('cidade', models.CharField(blank=True, max_length=40)),
                ('endereço', models.CharField(blank=True, max_length=80)),
                ('nome_contato', models.CharField(blank=True, max_length=40)),
                ('num_contato', models.CharField(blank=True, max_length=40)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('valor_multa', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('forma_pagto', models.TextField(blank=True)),
                ('dt_ult_pagto', models.DateField(blank=True)),
                ('dt_fim_contrato', models.DateField(blank=True)),
                ('dt_prox_reuniao', models.DateField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categoria')),
            ],
        ),
    ]
