# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180108_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='dt_fim_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='dt_prox_reuniao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='dt_ult_pagto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
