# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180115_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
    ]
