# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180115_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='dt_implant',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='dt_ult_alter',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='usuar_implant',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='categoria',
            name='usuar_ult_alter',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='dt_implant',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='dt_ult_alter',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='usuar_implant',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='usuar_ult_alter',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='dt_implant',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='dt_ult_alter',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='usuar_implant',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='usuar_ult_alter',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
