# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180116_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo_orcamento',
            name='dt_implant',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anexo_orcamento',
            name='dt_ult_alter',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anexo_orcamento',
            name='usuar_implant',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='anexo_orcamento',
            name='usuar_ult_alter',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='anexo_orcamento',
            name='file_name',
            field=models.FileField(upload_to='', verbose_name='Arquivo'),
        ),
    ]
