# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180117_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo_orcamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
