# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_anexo_orcamento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='assinado',
            field=models.BooleanField(default=False),
        ),
    ]
