# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_orcamento_assinado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='dt_assinado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
